### ISSUE TITLE
Feature request - output file & multi ASREPROAST

### ISSUE THREAD

**Issue by Lexus89** [GhostPack/Rubeus#1]
First of all, great tool! I have noticed i could use a function to create output files for hashes for stuff like roasting (hashcat format would be best) and perhaps methods to multi ASREProast by loading a userlist or even bruteforcing usernames and automatically checking each user for the no preauth.

**Comment by HarmJ0y** [comment]
Thanks for the feedback, this is definitely on the list to consider.

**Comment by vysec** [comment]
@Lexus89 if you're already on the domain, why do you need to bruteforce...

**Comment by Lexus89** [comment]
@vysec Asreproast does not require domain access

**Comment by vysec** [comment]
I'm reading from here: http://www.harmj0y.net/blog/activedirectory/roasting-as-reps/

**Comment by HarmJ0y** [comment]
I'll consider the output file option, but you are correct that ASRepRoasting does not need domain access, _assuming the user name to roast and DC name are known ahead of time_. I can potentially have the default functionality be similar to Kerberoasting, where (given a basic domain-authenticated context) users without preauth are enumerated and roasted, but I will likely not incorporate functionality that bruteforces user names.

**Comment by HarmJ0y** [comment]
This is implemented with version 1.3.2 https://github.com/GhostPack/Rubeus/commit/805cb798fbbf2fc187acc34d53d0abd973b36cfd

-**aspreroast** behavior now matches **kerberoast**
-**asreproast**/**kerberoast** both now have "/outputfile:X" for hash output

**Comment by Lexus89** [comment]
@HarmJ0y Thanks for implementing. Does this mean loading a userlist won't be implemented as well? Shame for all those NULL-sessions still around :)
