### ISSUE TITLE
Precompiled binaries?

### ISSUE THREAD

**Issue by r3k2** [GhostPack/Rubeus#123]
Hello some of us use linux as our main OS and will be nice like other tools to have binaries that we can have on the side to upload on our pentests or CTF's. is a pain to startup KVM/Qemu whole lab for just one binary to compile it.  thanks

**Comment by HarmJ0y** [comment]
As per the the [README](https://github.com/GhostPack/Rubeus/#compile-instructions), we currently do not intend on providing compiled versions of any GhostPack binaries.

There are other public resources [like this repo](https://github.com/Flangvik/SharpCollection) that provide builds of various offensive projects if needed on CTFs/etc.
