### ISSUE TITLE
Can a golden attack be done using the same user as the logged in user?

### ISSUE THREAD

**Issue by rick-engle** [GhostPack/Rubeus#151]
I noticed that if you use the Rubeus golden attack that it only seems to give you elevated privileges if you use a different userID than the one you are signed in with.   So, for example, if you are logged in with mydomain\jeffl, you can't use the parameter /user:jeffl in the Rubeus command line.

I am using this command:
Rubeus golden /newpac /rc4:09a4891da94d1f2522afdc7c4dd09b7b /ldap /user:ronhd /groups:512 /endtime:10y /ptt

So, let's say you only have access to one compromised AD user ID/password and are logged in as that user, is there a way to override the logged in user's ticket and replace it with the one that is created via the golden ticket attack?

Thanks.

**Comment by 0xe7** [comment]
I'm not sure what you mean, if you want to grant extra privileges to a specific account, use the `/groups` argument and add a privileged group to that. It's less opsec because the groups will be visible in 4627 events, but it's possible.

Using `/ppt` or `ptt /ticket:TGT` overwrites the current sessions TGT, you can end up with some unusual behaviour if you are doing this into a domain-joined session but it may work for what you want, if I'm understanding you correctly

**Comment by rick-engle** [comment]
Well what I meant is that as long as I use a domain user other than the one I am logged into the current session with, this command works:
Rubeus golden /newpac /rc4:09a4891da94d1f2522afdc7c4dd09b7b /ldap /user:ronhd /groups:512 /endtime:10y /ptt
Otherwise, if I use that command against the same userID as the one I am logged in as then it does generate the ticket but I don't elevate the privileges of my currently logged in userID.
So let's say I try a DIR \\DOMAINCONTROLLERNAME\C$ before the attack, I'll get Access is denied.
And after I execute the Rubeus command, I'll still get the Access is denied error.
I am already using the /groups parameter which does work completely if I use a different user.
I was just hoping there was a way to completely replace the current user's session TGT (that only has user privileges) with the golden ticket's ticket, elevating the privileges.
I do have a solution as originally described which works great, but that requires I know 2 rather than just 1 domain credential.

**Comment by 0xe7** [comment]
I don't know why it's going wrong for you but `ptt` does replace the current sessions TGT.

Can we not use github issues for these types of questions, this should be for issues directly related to the project, a good place to ask questions like this is the BloodHound Gang slack, it has many channels for all different topics and many very knowledgeable people.

https://bloodhoundgang.herokuapp.com/

Thanks.
