### ISSUE TITLE
ASREP2Kirbi and System.Runtime.InteropServices.WindowsRuntime causing issues with .net 4.0 

### ISSUE THREAD

**Issue by lassehauballe** [GhostPack/Rubeus#158]
Seems that the latest merge to include the command ASREP2Kirbi.cs, which uses System.Runtime.InteropServices.WindowsRuntime isn't part of .net 4.0 or 3.5? But only 4.5 and newer. 

Not sure if it is just me.

**Comment by 0xe7** [comment]
should be fixed now, the include was unnecessary anyway, so just removed it
