### ISSUE TITLE
DLL Search Order Hijacking vulnerability in Rubeus

### ISSUE THREAD

**Issue by paoloc94-df** [GhostPack/Rubeus#179]
There is currently a DLL search order hijacking vulnerability in Rubeus. The executable tries to load secur32.dll and sspicli.dll from the path where it is run from, resulting in code execution if a dll with the same name as the ones above is provided (media attached for reference). Verified on the latest version of Rubeus.

![Rubeus_procmon](https://github.com/GhostPack/Rubeus/assets/154344180/6e81dcb8-a91d-4438-a68b-9b818cad5af6)
https://github.com/GhostPack/Rubeus/assets/154344180/61d74c33-3cdf-4e58-9724-83c811bfd118

**Comment by CCob** [comment]
DLL search order hijacks are not vulns imo.  The issue is writable folder, equally I could backdoor the Rubeus exe itself.  So with that in mind, closing as wontfix
