### ISSUE TITLE
Unhandled Rubeus exception: The handle is invalid.

### ISSUE THREAD

**Issue by toughiv** [GhostPack/Rubeus#181]
Command run:

`execute-assembly C:\Tools\Rubeus\Rubeus\bin\Release\Rubeus.exe triage`

Output:

![Rubeus_Error](https://github.com/GhostPack/Rubeus/assets/71173147/32914cf8-5bb1-4292-9fc7-259c372ebcd8)

Misc:
Didn't recompile with .NET 4.8, used 4.0 (VS 2019)

**Comment by wwallace** [comment]
Exact same issue. Was getting a different error on a previous version when doing `renew`, thought it was about time to upgrade today, and seeing the same thing, but only with `execute-assembly`.

**Comment by jordangalida** [comment]
Same problem. Using inline execute-assembly still works for me though.

**Comment by 0xe7** [comment]
should be fixed by PR #182
