### ISSUE TITLE
Unhandled Rubeus Exception when dealing with Kerberos tickets as SYSTEM user in v2.3.2.

### ISSUE THREAD

**Issue by cedBouch** [GhostPack/Rubeus#184]
# Steps leading to the issue.
1. RDP as DA in a Windows Server 2019 Standard with Windows 10 OS, x64 arch.
2. Execute PowerShell as administrator and elevate to SYSTEM with `PsExec64.exe -i -s cmd.exe`.
3. Execute any Kerberos ticket related command like `.\Rubeus.exe klist` and get exception.

![image](https://github.com/GhostPack/Rubeus/assets/30204871/eeb56305-b410-477a-8d23-67ea12aa76ef)

# What has been found to work
1. Executing as administrator instead of SYSTEM does not trigger the exception.
2. Executing commands that do not deal with tickets does not trigger the exception. Commands such as currentluid and hash.

![image](https://github.com/GhostPack/Rubeus/assets/30204871/26548041-9539-4f3c-95cb-dfa704ce1960)

Let me know if you need more info.

**Comment by 1chk0v** [comment]
Confirming the issue with SYSTEM.
