### ISSUE TITLE
Consider adding a Rubeus.exe.config

### ISSUE THREAD

**Issue by CaledoniaProject** [GhostPack/Rubeus#20]
To run on .NET 4.X without recompile and retargeting, you need to create a `Rubeus.exe.config`:

```
<?xml version="1.0" encoding="utf-8"?>
<configuration>
    <startup>
        <supportedRuntime version="v2.0.50727"/>
        <supportedRuntime version="v4.0"/>
    </startup>
</configuration>
```

Can you add it to the VS project?

**Comment by HarmJ0y** [comment]
I haven't messed with this before- where/how should this be added to the project?

**Comment by CaledoniaProject** [comment]
This should work: [To configure your app to run on the .NET Framework 4 or later versions
](https://docs.microsoft.com/en-us/dotnet/framework/migration-guide/how-to-configure-an-app-to-support-net-framework-4-or-4-5#to-configure-your-app-to-run-on-the-net-framework-4-or-later-versions)

BTW: [SharpHound](https://github.com/BloodHoundAD/SharpHound) is also generating a SharpHound.exe.config file

**Comment by HarmJ0y** [comment]
Thanks, will look into this!

**Comment by egypt** [comment]
The config has to live on the filesystem alongside the exe when you run it, correct? I haven't found a definitive way to build an executable as a single file that works on both 2.x/3.x and 4.0+.

**Comment by CaledoniaProject** [comment]
@egypt Yes, you need to put the config in the same directory, e.g

```
SharpHound.exe  SharpHound.exe.config
```

I just compile Rubeus against .NET 3.5 and add the config file and it would run on .NET 4.X.

**Comment by HarmJ0y** [comment]
Based on Microsoft's description [here](https://docs.microsoft.com/en-us/dotnet/framework/migration-guide/how-to-configure-an-app-to-support-net-framework-4-or-4-5), it appears that you are correct @egypt - there [doesn't appear to be a way](https://stackoverflow.com/questions/24270489/embedding-supportedruntime-into-exe-file) to embed a config into the .exe itself.

As a file on disk is required, and as Rubeus is meant to be weaponized through offensive assembly execution, the best option at this point is to compile versions for 3.5 and 4.0 and use as needed. I'm going to mark this as closed for now.
