### ISSUE TITLE
Getting the domain controller

### ISSUE THREAD

**Issue by raithedavion** [GhostPack/Rubeus#21]
I was having an issue getting the domain controller during my testing of the kerberoasting functionality.  The issue seems to be the function GetDCName().  Note, I ran this with and without the built in impersonation, and using the SimpleImpersonation library.  My solution for my very specific use case was to modify the GetDCName() code as follows:

`if (ERROR_SUCCESS == val)
            {
                domainInfo = (Interop.DOMAIN_CONTROLLER_INFO)Marshal.PtrToStructure(pDCI, typeof(Interop.DOMAIN_CONTROLLER_INFO));
                string dcName = domainInfo.DomainControllerName;
                Interop.NetApiBufferFree(pDCI);
                return dcName.Trim('\\');
            }
            else
            {
                try
                {
                    **string pdc = System.DirectoryServices.ActiveDirectory.Domain.GetCurrentDomain().PdcRoleOwner.Name;
                    return pdc;**
                }
                catch
                {
                    string errorMessage = new Win32Exception((int)val).Message;
                    Console.WriteLine("\r\n  [X] Error {0} retrieving domain controller : {1}", val, errorMessage);
                    Interop.NetApiBufferFree(pDCI);
                    return "";
                }
            }`

This seems to have solved my little issue.  But just wanted to let you know.

**Comment by HarmJ0y** [comment]
I integrated this into master with https://github.com/GhostPack/Rubeus/issues/21
