### ISSUE TITLE
Alternate credentials issue

### ISSUE THREAD

**Issue by whoot** [GhostPack/Rubeus#33]
When using alternate credentials, the /creduser must be specified with: **/creduser:DOMAIN.FQDN\USER**

However, this does not work and Rubeus can not connect to the DC:
```
.\Rubeus.exe kerberoast /creduser:example.com\demo /credpassword:Password123 /dc:192.168.0.38 /domain:example.com

   ______        _
  (_____ \      | |
   _____) )_   _| |__  _____ _   _  ___
  |  __  /| | | |  _ \| ___ | | | |/___)
  | |  \ \| |_| | |_) ) ____| |_| |___ |
  |_|   |_|____/|____/|_____)____/(___/

  v1.4.2


[*] Action: Kerberoasting

[*] NOTICE: AES hashes will be returned for AES-enabled accounts.
[*]         Use /ticket:X or /tgtdeleg to force RC4_HMAC for these accounts.

[*] Target Domain          : example.com

[X] Error creating the domain searcher: The LDAP-Server is not available.
```

But when I am using the IP of the DC, everything works as expected:
```
.\Rubeus.exe kerberoast /creduser:192.168.0.38\demo /credpassword:Password123 /dc:192.168.0.38 /domain:example.com

   ______        _
  (_____ \      | |
   _____) )_   _| |__  _____ _   _  ___
  |  __  /| | | |  _ \| ___ | | | |/___)
  | |  \ \| |_| | |_) ) ____| |_| |___ |
  |_|   |_|____/|____/|_____)____/(___/

  v1.4.2


[*] Action: Kerberoasting

[*] NOTICE: AES hashes will be returned for AES-enabled accounts.
[*]         Use /ticket:X or /tgtdeleg to force RC4_HMAC for these accounts.

[*] Target Domain          : example.com
[*] Using alternate creds  : 192.168.0.38\demo
[*] Searching path 'LDAP://192.168.0.38' for Kerberoastable users

[X] No users found to Kerberoast!
```

**Comment by VbScrub** [comment]
This happened to me as well. I commented out these lines in the roast.cs file (line 93 to line 104) and that made it work fine with the normal domain name:

` 
using (PrincipalContext pc = new PrincipalContext(ContextType.Domain, cred.Domain))
                        {
if (!pc.ValidateCredentials(cred.UserName, cred.Password))
                            {
                                Console.WriteLine("\r\n[X] Credentials supplied for '{0}' are invalid!", userDomain);
                                return;
                            }
                            else
                            {
                                Console.WriteLine("[*] Using alternate creds  : {0}\r\n", userDomain);
                            }
                        }
`
Its only trying to validate that the credentials work, so no great loss removing it if you know the credentials are good anyway
