### ISSUE TITLE
asktgt Asn1.AsnException: value overflow

### ISSUE THREAD

**Issue by bashexplode** [GhostPack/Rubeus#47]
Just pulled the latest and tried a run of the mill asktgt, attempted with RC4 and AES128 hashes.
```
PS C:\Dev\Rubeus-master\Rubeus\bin\Release> .\Rubeus.exe asktgt /user:<redacted> /aes128:<redacted> /domain:<redacted> /dc:<redacted>

[*] Action: Ask TGT

[*] Using aes128_cts_hmac_sha1 hash: <redacted>
[*] Building AS-REQ (w/ preauth) for: '<redacted>\<redacted>'

[!] Unhandled Rubeus exception:

Asn1.AsnException: value overflow
   at Asn1.AsnElt.Decode(Byte[] buf, Int32 off, Int32 maxLen, Int32& tc, Int32& tv, Boolean& cons, Int32& valOff, Int32& valLen)
   at Asn1.AsnElt.Decode(Byte[] buf, Int32 off, Int32 len, Boolean exactLength)
   at Rubeus.Ask.InnerTGT(String userName, String domain, String keyString, KERB_ETYPE etype, String outfile, Boolean ptt, String domainController, LUID luid, Boolean describe, Boolean verbose)
   at Rubeus.Ask.TGT(String userName, String domain, String keyString, KERB_ETYPE etype, String outfile, Boolean ptt, String domainController, LUID luid, Boolean describe)
   at Rubeus.Commands.Asktgt.Execute(Dictionary`2 arguments)
   at Rubeus.Domain.CommandCollection.ExecuteCommand(String commandName, Dictionary`2 arguments)
   at Rubeus.Program.MainExecute(String commandName, Dictionary`2 parsedArgs)
```

**Comment by HarmJ0y** [comment]
I've tried to look into this, but have been unable to recreate at this point. I'll keep trying to dive in when I have more time.

**Comment by bashexplode** [comment]
Let me know if you need more information about the domain, etc. I'll post what I can, but redacted. Otherwise I'm in the Bloodhound gang slack, we can talk through it if needs be.

**Comment by okazymyrov** [comment]
I do not see the exception error in 0754532. However, /aes128, /aes256 and /des options do not work in my environment. No issues for clear password auth and /rc4.

**Comment by leechristensen** [comment]
Pretty sure this bug is due to not waiting until all data has been read from the TCP stream.  Added an [temporary hack](https://github.com/GhostPack/Rubeus/blob/master/Rubeus/lib/Networking.cs#L154-L155) that will probably make it work in most cases, but there's still a chance it'll happen.

**Comment by jeremythastings** [comment]
I actually do not receive this error if I pass the base64 encoded ticket string instead of a file.

**Comment by jeremythastings** [comment]
I believe the error may be in parsing the path for the ticket file? I compiled with the Thread.Sleep temporary hack and immediately get the same error as if its breaking before reaching Thread.Sleep. I recompiled and made it 30secs and just passed the raw base64 encoded ticket as a string and it works as expected, including sleeping for 30 seconds before completing.

Also, need to add "using System.Threading" before testing with Thread.Sleep for anyone trying to use this.

**Comment by bashexplode** [comment]
I know it's been a few months since the hack @leechristensen, but I just retested the latest version in the same environment and all is working again! Closing, appreciate the turnaround!

**Comment by leechristensen** [comment]
Thanks! I appreciate you taking the time to confirm and let us know @bashexplode !

**Comment by bashexplode** [comment]
for sure! it actually looks like the real fix was changing the following in the Ask class:    
> byte[] reqBytes = AS_REQ.NewASReq(userName, domain, keyString, etype);  
  
to: 
  
> AS_REQ userHashASREQ = AS_REQ.NewASReq(userName, domain, keyString, etype);  
> byte[] reqBytes = userHashASREQ.Encode().Encode();  
  
So whatever changes were made to the format of the AS_REQ class + the Encoding conversion is where it was dying.  
  
Thanks again! Really appreciate all your work!
