### ISSUE TITLE
Replace checks for "NT Authority\System" string with SID comparison

### ISSUE THREAD

**Issue by VbScrub** [GhostPack/Rubeus#50]
There's a few places where the code checks to see if it is running as Local System by doing this: 

```
var currentName = WindowsIdentity.GetCurrent().Name;
if (currentName == "NT AUTHORITY\\SYSTEM")
```

Which I'm pretty sure won't work on non English versions of Windows (because in French for example the account name would be "AUTORITE NT/Systeme"). 
Plus it just generally seems like a better idea to compare our SID to the well known Local System SID, rather than comparing account name strings. So I propose changing to this instead:

```
var currentSid = WindowsIdentity.GetCurrent().User;
if (currentSid.IsWellKnown(WellKnownSidType.LocalSystemSid))
```

**Comment by HarmJ0y** [comment]
Thanks for the catch! This should be fixed now with https://github.com/GhostPack/Rubeus/commit/732303e2f182d25e81ae25b4351782b2d0f061d0

**Comment by VbScrub** [comment]
I was literally just making a PR for this and was so confused when I couldn't find the references to NT Authority\System anymore haha thanks for doing it for me
