### ISSUE TITLE
What is the purpose of sanitization for output files?

### ISSUE THREAD

**Issue by okazymyrov** [GhostPack/Rubeus#63]
In asktgt the output file is sanitized when a full path for ticket output is used (e.g., "C:\Folder 1\Folder2\ticket.kirbi"). The result is saved into the folder with rubeus.exe instead of provided output. What is the purpose of sanitization?

Ref:
https://github.com/GhostPack/Rubeus/blob/075453288a95c69696803df8a1693c8401766a12/Rubeus/lib/Ask.cs#L206

**Comment by leezp** [comment]
output doesn't ;
i tried Rubeus.exe monitor /output:.\a.txt

**Comment by leezp** [comment]
@HarmJ0y  can you fix "outfile" parameter? doesn't work 
![image](https://user-images.githubusercontent.com/16287528/106141377-f2286400-61aa-11eb-9621-c86f3d298d63.png)

**Comment by leezp** [comment]
![image](https://user-images.githubusercontent.com/16287528/106141447-0d936f00-61ab-11eb-99e3-cbdbda3ef1d5.png)

**Comment by HarmJ0y** [comment]
The purpose of sanitization is to strip invalid characters from an output file name https://github.com/GhostPack/Rubeus/blob/afa7ca11a0695196781e920df047bd1951a6b47f/Rubeus/lib/Helpers.cs#L275-L283

**Comment by HarmJ0y** [comment]
@leezp The `/outfile` parameter is not valid for the `monitor` command. For future issues, please make sure to read either:

- The default Rubeus.exe help output
- The extensive [README.md](https://github.com/GhostPack/Rubeus/blob/master/README.md) or
- The [source of the command](https://github.com/GhostPack/Rubeus/blob/master/Rubeus/Commands/Monitor.cs) you're having issues with that controls the flags passed.

**Comment by leezp** [comment]
> @leezp The `/outfile` parameter is not valid for the `monitor` command. For future issues, please make sure to read either:
> 
> * The default Rubeus.exe help output
> * The extensive [README.md](https://github.com/GhostPack/Rubeus/blob/master/README.md) or
> * The [source of the command](https://github.com/GhostPack/Rubeus/blob/master/Rubeus/Commands/Monitor.cs) you're having issues with that controls the flags passed.

if you can add some enhancement and  fix it?

**Comment by okazymyrov** [comment]
Please note that the original issue was for **asktgt**, and not for **monitor**.
