### ISSUE TITLE
New PKInit / Smartcard features fail on FIPS enforced systems

### ISSUE THREAD

**Issue by ringt** [GhostPack/Rubeus#67]
New PKInit features fail when FIPS compliance is enforced.  SHA1Managed is not FIPS compliant.  Suggested code changes are available #66 .  It is a simple change to FIPS compliant classes as the classes have the same Methods.  Opening issue to call attention to the PR.

**Comment by HarmJ0y** [comment]
PR is landed, so closing this now.
