### ISSUE TITLE
KRB-ERROR (68) : KDC_ERR_WRONG_REALM

### ISSUE THREAD

**Issue by jeremythastings** [GhostPack/Rubeus#78]
C:/Windows/Temp/Rubeus.exe asktgs /ticket:REDACTED /service:CIFS/test-dc1.test.local 

I get the above error when using asktgs. Bi-directional trust between two forests and ticket is generated with rc4 trust key from recent hashdump. Any ideas on issue?

**Comment by jeremythastings** [comment]
I may have found the issue. After researching it appears in Windows this error occurs when a user requests a Kerberos TGT for a realm that is not hosted on the server to which they are authenticating.

Will double check DCs for forest and close issue.

**Comment by jimmio** [comment]
@jeremythastings Did you come to any conclusions about this?

**Comment by jeremythastings** [comment]
Yeah sorry for the delayed response. I was receiving this error while running Rubeus on a secondary DC. The below article made me consider that, ran it on the primary DC, and had success. So ensure that you’re on the DC that hosts the realm. Does this make sense to you guys?
 http://vanbortel.blogspot.com/2008/01/kerberos-errors_25.html?m=1

**Comment by jimmio** [comment]
In my case I was getting the KDC_ERR_WRONG_REALM error but an upgrade to Rubeus 1.5 fixed it. I did not have to run the command from a DC.

**Comment by HarmJ0y** [comment]
Since it looks like things are resolved I'm going to mask this as closed, feel free to reopen if it's still an issue.
