### ISSUE TITLE
About [X] KRB-ERROR (75) : 75

### ISSUE THREAD

**Issue by YangSirrr** [GhostPack/Rubeus#93]
hello, in my test environment to test something, I find the version of 1.6.4 have some wrong OR BUG?
like this my command such as to ptt exec:
	Rubeus.exe asktgt  /user:OWA2013$ /ptt /certificate:XXX

the result have some wrong like this
  v1.6.4 

[*] Action: Ask TGT

[*] Using PKINIT with etype rc4_hmac and subject: CN=OWA2013$ 
[*] Building AS-REQ (w/ PKINIT preauth) for: 'rootkit.org\OWA2013$'

[X] KRB-ERROR (75) : 75

but my cert ticket is right I don't know why the program have not to ptt success
I need your help, thank you very much!

**Comment by darkoperator** [comment]
That error is for

Kerberos client name does not match name bound to the client certificate. ... Kerberos KDC name does not match name bound to the KDC certificate.

**Comment by HarmJ0y** [comment]
To second what @darkoperator stated, this is a [KDC_ERR_CLIENT_NAME_MISMATCH](https://www.eventid.net/articles/article_kerberos_error_codes.asp) error which happens when the client name supplied does not match the name in the certificate.

For more information on certificate mappings, see [3.1.5.2.1 Certificate Mapping](https://docs.microsoft.com/en-us/openspecs/windows_protocols/ms-pkca/01c4acb8-c366-4d31-93a5-fbf2d59c8b27) of **[MS-PKCA]**.

**Comment by YangSirrr** [comment]
T

> 该错误是因为 Kerberos 客户端名称与绑定到客户端证书的名称不匹配。... Kerberos KDC 名称与绑定到 KDC 证书的名称不匹配。
> […](#)
> Sent from my iPhone
> On Aug 15, 2021, at 10:52 AM, Yangsir ***@***.***> wrote: KRB-ERROR (75)

thankyou，maybe my environment OR  testing process have some mistake, yestarday I attack the environment againg, I found I no longer meet this problem,  Maybe really because the KDC name&cert 's problem. Now I success to use the cert to PTT

**Comment by YangSirrr** [comment]
> 第二个@darkoperator所说的，这是一个[KDC_ERR_CLIENT_NAME_MISMATCH](https://www.eventid.net/articles/article_kerberos_error_codes.asp)错误，当提供的客户端名称与证书中的名称不匹配时会发生。
> 
> 有关证书映射的更多信息，请参见[3.1.5.2.1证书映射](https://docs.microsoft.com/en-us/openspecs/windows_protocols/ms-pkca/01c4acb8-c366-4d31-93a5-fbf2d59c8b27)的**[MS-PKCA] **。

thankyou，maybe my environment OR  testing process have some mistake, yestarday I attack the environment againg, I found I no longer meet this problem,  Maybe really because the KDC name&cert 's problem. Now I success to use the cert to PTT

**Comment by Startr4ck** [comment]
Got Same error Code.
Guess may Winddows 2019 Cause wrong. But 2016 Everything fine.

**Comment by Startr4ck** [comment]
> 得到相同的错误代码。 猜测可能是 Windows 2019 导致错误。但是2016年一切都很好。

Even same client name and certificate name. may Rubeus faces bug

**Comment by Startr4ck** [comment]
face the same problem . may the server you test  not install ad cs ~

**Comment by Sybrid203** [comment]
Does someone know why this happens?
